### ISSUE TITLE
Update regular expression: DATASET_KEY_PATTERN

### ISSUE THREAD

**Issue by Wilfongjt** [datadotworld/data.world-py#100]
The current DATASET_KEY_PATTERN expression doesn't match dataset names that use underscores.  GR-drains is ok but GR_drains breaks the match. Data.world supports underscores and hyphens.

**Comment by rflprr** [comment]
Hi, @Wilfongjt.

data.world doesn't allow underscores. As you can see in the example below, if I attempt to create a dataset named `GR_drains` under my `rflprr` account, the URL for it will automatically be established as `https://data.world/rflprr/grdrains`, where `rflprr/grdrains` is the dataset key.

![image](https://user-images.githubusercontent.com/1487471/43742366-4488780e-9997-11e8-9d11-e4a3f5066f55.png)

Let me know in case this doesn't make sense. If you are still having trouble, let me now what you are trying to accomplish and I will try to help.
