### ISSUE TITLE
ERROR: datadotworld 1.6.0 has requirement flake8<3.4.1a,>=2.6.0, but you'll have flake8 3.6.0 which is incompatible.

### ISSUE THREAD

**Issue by rjurney** [datadotworld/data.world-py#110]
When I install `datadotworld` on Ubuntu 18.04 Linux with Anaconda Python 3.6.7 in a virtualenv setup around Apache superset's `release--0.31` branch, I get the following error:

```python
ERROR: datadotworld 1.6.0 has requirement flake8<3.4.1a,>=2.6.0, but you'll have flake8 3.6.0 which is incompatible.
```

Is the requirement of `datadotworld` for `flake8<3.4.1a` a hard requirement or is this something that could be relaxed?

**Comment by jboutros** [comment]
I don't think it's a hard requirement, taking a look now to make sure we can upgrade it. Also, it's a dev dependency, but listed under runtime deps in setup.py - moving it should remove the dependency at install time unless you're contributing.

**Comment by rjurney** [comment]
@jboutros Ok, cool thanks
