### ISSUE TITLE
RestApiClient.create_dataset() should return dataset id

### ISSUE THREAD

**Issue by ericbusboom** [datadotworld/data.world-py#26]
The RestApiClient.create_dataset() method currently returns None, which makes it difficult to automate later processing on the created dataset. It should return the dataset id of the newly created dataset, or the return value from RestApiClient.get_dataset()

**Comment by rflprr** [comment]
Thank you for the feedback.
This project has been updated so that create_dataset() will return the URL of the new dataset if the server responds with one. We'll update our REST API over the next few days to ensure that it does that.

**Comment by rflprr** [comment]
Hi, @ericbusboom. This is fixed and you should be able to get the URL of the new dataset upon creation now.
