### ISSUE TITLE
API Can't Handle Hierarchical Zip Contents

### ISSUE THREAD

**Issue by ericbusboom** [datadotworld/data.world-py#27]
After uploading a ZIP file with hierarchical path names, calling get_dataset() fails, with: 

```
  File "/Volumes/Storage/proj/virt/metatab3/lib/python3.5/site-packages/datadotworld/client/_swagger/models/file_summary_response.py", line 80, in name
    raise ValueError("Invalid value for `name`, must be a follow pattern or equal to `/^[^/]+$/`")
ValueError: Invalid value for `name`, must be a follow pattern or equal to `/^[^/]+$/`
```

The file name produced by the server has '/' in it, but the API does not allow these in names. 

Specifically, the problem seems to be either (a) the server generates incorrect names or (b) the validation pattern is wrong at swagger-dwapi-def.json : definitions.FileSummaryResponse.properties.name.pattern

**Comment by rflprr** [comment]
Thank you for letting us know about this.
