### ISSUE TITLE
API Has Title Limit Not In Application

### ISSUE THREAD

**Issue by ericbusboom** [datadotworld/data.world-py#38]
I'm using the API to create datasets that have long titles, > 30 characters. Because the titles are used in keys, they must be truncated to the 30 character limit for keys, and the key apparently can't have ellipses ('...') at the end, so the title is truncated abruptly. 

The API will throw an exception on long title: 

> ValueError: Invalid value for `title`, length must be less than or equal to `30`

However, it appears that the web application does not enforce a 30 character limit, neither for the display titles nor the dataset key. 

It would be preferable if the API either removed the 30 character limit, or allowed for a display title that could be longer, with a separate value for the dataset key slug.

**Comment by rflprr** [comment]
@ericbusboom Thanks for this. You are right, the limit on the site has changed recently from 30 to 60 (enforced for the display title). The Python implementation hasn't been updated to reflect that yet. Possibly next week, or earlier if someone is willing to submit PR. :-)

**Comment by laconc** [comment]
With #56 merged, this issue has now been resolved.
