### ISSUE TITLE
Set and Report Resource Descriptions

### ISSUE THREAD

**Issue by ericbusboom** [datadotworld/data.world-py#41]
The API should report and allow to be set the resource descriptions.

**Comment by rflprr** [comment]
@ericbusboom, this is now a feature in our API and will add support for it in our python package sometime this week. There is one minor caveat with the API design that we still have to improve. If you add a file via URL, you can provide a description in the same request. If you upload an actual file, you'll need to provide the description in a follow-up request.

You can find additional info here: https://docs.data.world/documentation/api/updateDataset.html

**Comment by rflprr** [comment]
Fixed in https://github.com/datadotworld/data.world-py/releases/tag/v1.5.0
