### ISSUE TITLE
Add a way to set the token in Python

### ISSUE THREAD

**Issue by hardworkingcoder** [datadotworld/data.world-py#55]
This way I can handle multiple users at once.

**Comment by bryonjacob** [comment]
@hardworkingcoder what are your thoughts on how best this should work?  This is a little hack that I've written to be able to pass in a token directly into a data.world client constructor - you can do the same in your own code (i.e. create this local class called `InlineConfig` that extends `DefaultConfig`)  One thing we could do is just add this `InlineConfig` as a component that is part of the standard python SDK, I'm wondering if there's a better pattern for managing tokens for multiple users...  

```
from datadotworld.config import DefaultConfig
from datadotworld.datadotworld import DataDotWorld

class InlineConfig(DefaultConfig):
    def __init__(self, token):
        super(InlineConfig, self).__init__()
        self._auth_token = token

ddw = DataDotWorld(config=InlineConfig(token))
```

**Comment by bryonjacob** [comment]
@rflprr one thing to think about would be to implement a "token source" interface that takes a "user key" (could be an agent id or maybe a session key) and returns a token for that user.  then we could implement a "connection factory" that takes a "token source" in its constructor, and then returns activated connections based on "user key".  application implementors implement the "token source" and wire it in, allowing them to store tokens wherever they store user/session information.

**Comment by hardworkingcoder** [comment]
@bryonjacob I'm having trouble using api_client() with the code you gave me above. Could you please provide me code that works with api_client()?

**Comment by bryonjacob** [comment]
@hardworkingcoder can you be more specific, I'm not sure what you mean by `api_client()`...

**Comment by hardworkingcoder** [comment]
@bryonjacob 

This is my current non-working code.

```
def get_ddw():
    from datadotworld import DataDotWorld
    token = load_user(session['user_id']).ddw_access_token
    ddw = DataDotWorld(config=InlineConfig(token))
    client = datadotworld.api_client()
    return ddw, ddw_client
```

**Comment by hardworkingcoder** [comment]
@bryonjacob 

I tried passing InlineConfig to api_client. Got this exception

```
File "./app.py", line 134, in get_ddw
    client = datadotworld.api_client(InlineConfig(token))
  File "/home/main/dw_experiments_dev/env/local/lib/python2.7/site-packages/datadotworld/__init__.py", line 162, in api_client
    return _get_instance(profile).api_client
  File "/home/main/dw_experiments_dev/env/local/lib/python2.7/site-packages/datadotworld/__init__.py", line 45, in _get_instance
    else FileConfig(profile=profile))
  File "/home/main/dw_experiments_dev/env/local/lib/python2.7/site-packages/datadotworld/config.py", line 119, in __init__
    if profile.lower() != configparser.DEFAULTSECT.lower()
AttributeError: 'InlineConfig' object has no attribute 'lower'
```
My code is now:
```
from datadotworld.config import DefaultConfig
from datadotworld.datadotworld import DataDotWorld
import datadotworld

class InlineConfig(DefaultConfig):
    def __init__(self, token):
        super(InlineConfig, self).__init__()
        self._auth_token = token

def get_ddw(user_id):
    token = load_user(user_id).ddw_access_token
    ddw = DataDotWorld(config=InlineConfig(token))
    client = datadotworld.api_client(InlineConfig(token))
    return ddw, ddw_client

@app.route('/api/delete_file', strict_slashes=False, methods=['POST'])
def delete_file():
    ddw, ddw_client = get_ddw(session['user_id'])
    ddw_client.delete_files(request.form['owner'], request.form['id'], [request.form['filename']])
    return jsonify({'success': True})
```

**Comment by rflprr** [comment]
@hardworkingcoder, my hunch is that this is the problem:
```
client = datadotworld.api_client(InlineConfig(token))
```
Have you tried the following instead?
```
client = ddw.api_client
```

**Comment by hardworkingcoder** [comment]
@rflprr works now. Thank you!
