### ISSUE TITLE
Support all new API paths (up to API v0.9.0)

### ISSUE THREAD

**Issue by hardworkingcoder** [datadotworld/data.world-py#60]
I got this list by running.
```
import requests
import json
api_swagger = requests.get('https://api.data.world/v0/swagger.json').text
api_swagger = api_swagger.encode('ascii', 'ignore').decode('ascii')
api_swagger = json.loads(api_swagger) 
python_swagger = requests.get('https://raw.githubusercontent.com/datadotworld/data.world-py/master/datadotworld/client/swagger-dwapi-def.json').text
python_swagger = python_swagger.encode('ascii', 'ignore').decode('ascii')
python_swagger = json.loads(python_swagger) 
print set(api_swagger['paths'].keys()) - set(python_swagger['paths'].keys())
```

**Comment by rflprr** [comment]
@hardworkingcoder looks like the right set of new endpoints.
In addition:
1. `PUT:/datasets/{owner}/{id}` and `PATCH:/datasets/{owner}/{id}` now allow users to change a dataset's title
2. `PUT:/datasets/{owner}/{id}` and `PATCH:/datasets/{owner}/{id}` consistently require `title` and `visibility` to be specified

**Comment by bryonjacob** [comment]
I just ran across a need for this today, as well - @hardworkingcoder are you planning to work on this and submit a PR?  I don't want to duplicate effort - happy to collaborate, review a PR, etc. - whatever it takes to get these functions added to the SDK!  thanks!

**Comment by hardworkingcoder** [comment]
@bryon I'm struggling with debugging the failing tests for
https://github.com/datadotworld/data.world-py/pull/61
