### ISSUE TITLE
Append to existing file

### ISSUE THREAD

**Issue by ivotron** [datadotworld/data.world-py#76]
It would be useful if a file can be extended without having to read its content first.

**Comment by rflprr** [comment]
Hi, @ivotron. Thanks for the feedback. We have just recently released a new API endpoint that you can use to do just that. You can learn about it here: https://apidocs.data.world/v0/streams/append-records-to-a-stream

Unfortunately, we don't have a python wrapper for it yet, so you'd have to write the code to hit it. Hopefully in a week or two we will.

**Comment by ivotron** [comment]
Cool! It's not urgent on my end, so I can wait. Thanks!

**Comment by rflprr** [comment]
Fixed by https://github.com/datadotworld/data.world-py/pull/82
