### ISSUE TITLE
setters should not aggressively validate on reads

### ISSUE THREAD

**Issue by bryonjacob** [datadotworld/data.world-py#88]
trying to do a simple GET of datasets through data.world-py 1.5.0
```
        datasets = dw.api_client.fetch_datasets()
```

getting the following:
```
...
  File "/Users/bryon/.virtualenvs/datadotworld-bryon-labs/lib/python3.6/site-packages/datadotworld/client/_swagger/models/file_summary_response.py", line 70, in __init__
    self.description = description
  File "/Users/bryon/.virtualenvs/datadotworld-bryon-labs/lib/python3.6/site-packages/datadotworld/client/_swagger/models/file_summary_response.py", line 153, in description
    raise ValueError("Invalid value for `description`, length must be greater than or equal to `1`")
ValueError: Invalid value for `description`, length must be greater than or equal to `1`
```
the offending code is:
https://github.com/datadotworld/data.world-py/blob/v1.5.0/datadotworld/client/_swagger/models/file_summary_response.py#L152-L153

since the value is coming back from the server, this validation is incorrect - either there's a defect on the server allowing this value to sometimes be empty, or (more likely) the python SDK should relax when deserializing server requests.  

You should never get an "invalid data" error on a GET.

**Comment by rflprr** [comment]
Blocked by: https://github.com/datadotworld/dwapi-spec/issues/70

**Comment by rflprr** [comment]
Fixed by https://github.com/datadotworld/data.world-py/pull/90
