### ISSUE TITLE
Automate conda-forge release

### ISSUE THREAD

**Issue by rflprr** [datadotworld/data.world-py#93]

**Comment by rflprr** [comment]
Would you be willing to help us with this, @pmlandwehr?

**Comment by pmlandwehr** [comment]
Hey - the best solution would be to add someone to the list of maintainers of the conda-forge recipe. That can be you if you'd like, @rflprr.  There's now a handy bot that should take care of trivially updating the version, but its commits need to be merged and if the requirements get changed they'll need to be modified by hand.

**Comment by pmlandwehr** [comment]
I would recommend reviewing the [conda-forge docs](https://conda-forge.org/docs/) and the [conda docs](https://conda.io/docs/). The most important notes are:
* If you want to make a new build, fork the feedstock, update, wait for the CI to finish and merge.
* Make sure that you re-render the feedstock to keep it up-to-date with the latest version of conda-smithy and the latest CI control scripts. (Re-rendering will have no impact if everything is current.
* Make sure checksums, pointers, to source tarballs, and all requirements (generally lifted from `setup.py` are current. conda-forge doesn't do much internal testing, so a bad requirement may be missed by the scripts.

**Comment by laconc** [comment]
The feedstock lives at https://github.com/conda-forge/datadotworld-py-feedstock.
